print("* g o a t s e x * g o a t s e x * g o a t s e x *") 
print("g                                               g")  
print("o /     \             \            /    \       o")  
print("a|       |             \          |      |      a")  
print("t|       `.             |         |       :     t")  
print("s`        |             |        \|       |     s")  
print("e \       | /       /  \\\   --__ \\       :    e")  
print("x  \      \/   _--~~          ~--__| \     |    x")  
print("*   \      \_-~                    ~-_\    |    *")  
print("g    \_     \        _.--------.______\|   |    g")  
print("o      \     \______// _ ___ _ (_(__>  \   |    o")  
print("a       \   .  C ___)  ______ (_(____>  |  /    a")  
print("t       /\ |   C ____)/      \ (_____>  |_/     t")  
print("s      / /\|   C_____) АСТРАЛ|  (___>   /  \    s")  
print("e     |   (   _C_____)\______/  // _/ /     \   e")  
print("x     |    \  |__   \\_________// (__/       |  x")  
print("*    | \    \____)   `----   --'             |  *")  
print("g    |  \_          ___\       /_          _/ | g ") 
print("o   |              /    |     |  \            | o ") 
print("a   |             |    /       \  \           | a ") 
print("t   |          / /    |         |  \           |t ") 
print("s   |         / /      \__/\___/    |          |s ") 
print("e  |         / /        |    |       |         |e ") 
print("x  |          |         |    |       |         |x ") 
print("* g o a t s e x * g o a t s e x * g o a t s e x *")
