x = input()
print ("Tissues without a triangular head lice be it with controller is the noodle man of ice pops and radio yes thanks")
x =input()
print("So even with I but he river flow amber rod with it.")
x =input()
print("You know bear mama said just keep boxing bitches")
x =input()
print("Where is narwhal pretty rhombus with monocle kitty")
x =input()
print("Has anyone really been far even as decided to use even go want to do look more like?")
x =input()
print("The sheep languished blue trains suffer")
x =input()
print("Windows books dogs hands run")
x =input()
print("Run desk making dinner sunglasses menu")
x =input()
print("Folders pile swimming red clouds")
x =input()
print("Sadness cups coffee printer power outage")
x =input()
print("Porch steps run come here")
x =input()
print("Dogs sleep chicken pencil trees")
x =input()
print("E-mail purple orange swims blackened")
x =input()
print("Garbage pink composition solely bags speak deodorant")
x =input()
print("Take sharpness filling soda cans")
x =input()
print("Wetness smooth dancing sheep")
x =input()
print("Horse paper handbags skipping forests play together")
x =input()
print("In worlds with pencils, schools page drink slime")
x =input()
print("ILoving living nectar of bees of pollen and butterflies run amok")
x =input()
print("Children bikes cars sliding ")
x =input()
print("Typing while sleeping and running while cat")
x =input()
print("Over the hills, cloud blue a shelf lay fuschia")
x =input()
print("Labels and rash, files are landing")
x =input()
print("Wall speaks windy hot mess")
x =input()
print("Brightness foresees the rug ")
x =input()
print("Dirty slime amidst antiquated hoopla")
x =input()
print("Take shirt slam crazy bike tires in afternoon")
x =input()
print("Amongst all confused working fly")
x =input()
print("Sensibly effort compound bed bubble")
x =input()
print("Kings sense jester realize tongues poetry")
x =input()
print("Words hard journal describe impossible")
x =input()
print("Religious hair coma machine idea hate")
x =input()
print("Interesting hospital interpreting description extreme encounter")
x =input()
print("Junction one distant fragile mine")
x =input()
print("Death wretched addled else finally chant mind sea backgrounds")
x =input()
print("Obey space cat disjointed languages swearing admit stranger bit dressing")
x =input()
print("Picture cake chocolate rambling UFO solar here fuse barking")
x =input()
print("Online signature basic color sleep ideas class")
x =input()
print("Dog bike cat sat sit down under sleep jump")
x =input()
print("Now later red cat boat ship house girl")
